@base_url = http://iramadibatu.myprojects.com

post {{base_url}}/api/v1/login
Content-Type: application/json

{
    "username": "testuser17",
    "password": "12345"
}

###

post {{base_url}}/api/v1/token/renew
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0yIiwiYXVkIjoiVGhlX0F1ZDIiLCJpYXQiOjE2MzM2OTE5NTcsImRhdGEiOnsidXNlcm5hbWUiOiJ0ZXN0dXNlcjE4In19.CqekAiXFZrcd_UV7f36FapHRZLaFYZ0d1s6r6bdQ1O0"
}

###

post {{base_url}}/api/v1/logout
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0yIiwiYXVkIjoiVGhlX0F1ZDIiLCJpYXQiOjE2MzM2OTI1MzQsImRhdGEiOnsidXNlcm5hbWUiOiJ0ZXN0dXNlcjE4In19.TpC6NGKY5o09lhv9myFL_f50A4eDw7iEAlWjvby4H7c"
}