@base_url = http://iramadibatu.myprojects.com/api/v1/dashboard/berita_acara
@active_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzQzODc5NjEsIm5iZiI6MTYzNDM4Nzk3MSwiZXhwIjoxNjM0Mzk1MTYxLCJkYXRhIjp7ImlkIjoiMjkiLCJmdWxsbmFtZSI6InRlc3QgdXNlciAxNyIsInVzZXJuYW1lIjoidGVzdHVzZXIxNyIsImVtYWlsIjoidGVzdHVzZXIxN0BleGFtcGxlLmNvbSIsImxldmVsIjoiYWRtaW4ifX0.s2vUvi8x1hPEFxXee8gSZgEYrWCoUp5mKFtrxyO-Cw8

// get all
get {{base_url}}
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###

// datatable 
post {{base_url}}/datatables
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "start": 0,
    "draw": 1,
    "length": 25
}
###

// create (test on postman)
# post {{base_url}}
# Authorization: Bearer {{active_token}}
# Content-Type: application/json
# X-Requested-With: XMLHttpRequest

# {
#     "nama": "John Doe 3",
#     "nip": "2020.123.124",
#     "pangkat_golongan": "d4",
#     "jabatan": "Test Jabatan 4"
# }

###

// update (test on postman)
# put {{base_url}}/5/update
# Authorization: Bearer {{active_token}}
# Content-Type: application/json
# X-Requested-With: XMLHttpRequest

# {
#     "nama": "John Doe 7",
#     "nip": "2020.123.127",
#     "pangkat_golongan": "d7",
#     "jabatan": "Test Jabatan 7"
# }

###
// delete
delete {{base_url}}/7/delete
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest


###
// delete multiple
delete {{base_url}}/delete/multiple
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "ids": [5, 6]
}