@base_url = http://inventory-barang.myprojects.com
@active_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzMyMjU2ODgsIm5iZiI6MTYzMzIyNTY5OCwiZXhwIjoxNjMzMjI5Mjg4LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.hX-yJksAx2rrhdZIZj0wzsKI46QPmsAtCy9t3XO_uxw

###

# get all

###

# get one

###

# create
post {{base_url}}/api/dashboard/firearms
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "inventory_type_id": "1",
    "firearms_type_id": "1",
    "firearms_brand_id": "2",
    "firearms_number": "asdffffjjf",
    "bpsa_number": "233ksdfkdfkkf",
    "condition": "normal",
    "description": "desc of something"
}

###

# update
put {{base_url}}/api/dashboard/firearms/1/update
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "inventory_type_id": "2",
    "firearms_type_id": "3",
    "firearms_brand_id": "4",
    "firearms_number": "asdffffjjf5",
    "bpsa_number": "233ksdfkdfkkf6",
    "condition": "damaged",
    "description": "desc of something7"
}

###

# delete
delete {{base_url}}/api/dashboard/firearms/3/delete
Authorization: Bearer {{active_token}}
X-Requested-With: XMLHttpRequest

###

# multi-delete
delete {{base_url}}/api/dashboard/firearms/delete/multiple
Authorization: Bearer {{active_token}}
X-Requested-With: XMLHttpRequest
Content-Type: application/json

{
    "ids": [9, 10]
}