@base_url = http://inventory-barang.myprojects.com
@active_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI5MTU4OTMsIm5iZiI6MTYzMjkxNTkwMywiZXhwIjoxNjMyOTE5NDkzLCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.l9Hltwz6X5MlTTQeMZj-bNZirPioSkji4kL7ptGeObo

# datatables
post {{base_url}}/api/dashboard/firearms-brands/datatables
Authorization: Bearer {{active_token}}

###

# create
post {{base_url}}/api/dashboard/firearms-brands
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "name": "SS2-V999 SUBSONICOL 3",
    "desc": "Desc of Senjata Sniper",
    "is_active": 1
}

###

# update status
put {{base_url}}/api/dashboard/firearms-brands/3/update/status
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "is_active": 0
}

###

# update data
put {{base_url}}/api/dashboard/firearms-brands/1/update
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "name": "SS2-V5 A1BOI",
    "desc": "Desc of SS2-V5 A1BOI",
    "is_active": 0
}

###

# delete data
delete {{base_url}}/api/dashboard/firearms-brands/26/delete
Authorization: Bearer {{active_token}}
X-Requested-With: XMLHttpRequest

###

# delete multiple
delete {{base_url}}/api/dashboard/firearms-brands/delete/multiple
Authorization: Bearer {{active_token}}
X-Requested-With: XMLHttpRequest
Content-Type: application/json

{
    "ids": [24, 25]
}