@base_url = http://inventory-barang.myprojects.com
@active_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzMxMzk1MzUsIm5iZiI6MTYzMzEzOTU0NSwiZXhwIjoxNjMzMTQzMTM1LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.6CbGU_-vY_sZJmJP-Q0PHaeO8z7kh-RySidHDkD0Hic