@base_url = http://inventory-barang.myprojects.com
@active_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzMxMzk1MzUsIm5iZiI6MTYzMzEzOTU0NSwiZXhwIjoxNjMzMTQzMTM1LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.6CbGU_-vY_sZJmJP-Q0PHaeO8z7kh-RySidHDkD0Hic


# GET ALL
get http://inventory-barang.myprojects.com/api/dashboard/inventory-types
Authorization: Bearer {{active_token}}

###

# GET ONE
get http://inventory-barang.myprojects.com/api/dashboard/inventory-types/5
Authorization: Bearer {{active_token}}

###

# GET DATATABLES
post http://inventory-barang.myprojects.com/api/dashboard/inventory-types/datatables
Authorization: Bearer {{active_token}}

###

# UPDATE STATUS
put {{base_url}}/api/dashboard/inventory-types/29/update/status
Authorization: Bearer {{active_token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "is_active": ""
}

###

# UPDATE DATA
put http://inventory-barang.myprojects.com/api/dashboard/inventory-types/29/update
Authorization: Bearer {{active_token}}
Content-Type: application/json

{
    "name": "Test Inventory Type Name",
    "desc": "Test Inventory Type Desc",
    "is_active": 1
}

###

# CREATE NEW
post http://inventory-barang.myprojects.com/api/dashboard/inventory-types
Authorization: Bearer {{active_token}}
Content-Type: application/json

{
    "name": "Tipe inventaris test 3",
    "desc": "Deskripsi untuk tipe inventaris test 3",
    "is_active": 1
}

###

# DELETE ONE
delete http://inventory-barang.myprojects.com/api/dashboard/inventory-types/26/delete
Authorization: Bearer {{active_token}}

###

# DELETE MULTIPLE
delete http://inventory-barang.myprojects.com/api/dashboard/inventory-types/delete/multiple
Authorization: Bearer {{active_token}}
Content-Type: application/json

{
    "ids": [10, 11]
}

###

