# GET ALL
get http://inventory-barang.myprojects.com/api/dashboard/inventory-types
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2NTUwNDQsIm5iZiI6MTYzMjY1NTA1NCwiZXhwIjoxNjMyNjU4NjQ0LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.st8JH1TYmxHrVFFskpCWfdfuCF_To6_0dvUOKORznrs

###

# GET ONE
get http://inventory-barang.myprojects.com/api/dashboard/inventory-types/5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2NTUwNDQsIm5iZiI6MTYzMjY1NTA1NCwiZXhwIjoxNjMyNjU4NjQ0LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.st8JH1TYmxHrVFFskpCWfdfuCF_To6_0dvUOKORznrs

###

# GET DATATABLES
post http://inventory-barang.myprojects.com/api/dashboard/inventory-types/datatables
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI1OTI3NDIsIm5iZiI6MTYzMjU5Mjc1MiwiZXhwIjoxNjMyNTk2MzQyLCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.gGQTPQxNEGILXckXnPUqyqa_-8M8hTvvpuei1Hdi8U4

###

# UPDATE STATUS
put http://inventory-barang.myprojects.com/api/dashboard/inventory-types/3/update/status
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2MTgyMzksIm5iZiI6MTYzMjYxODI0OSwiZXhwIjoxNjMyNjIxODM5LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.TzSimXg_rXZ5TjQPl9OTcJ8vWaMgY6O3gFwQph_o3qU
Content-Type: application/json

{
    "is_active": true
}

###

# UPDATE DATA
put http://inventory-barang.myprojects.com/api/dashboard/inventory-types/29/update
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2NTg4NDEsIm5iZiI6MTYzMjY1ODg1MSwiZXhwIjoxNjMyNjYyNDQxLCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.Iq4z_NUOjg8XXcjctlNe9XYNVADs9Ff5p6UkJxWZF2Y
Content-Type: application/json

{
    "name": "Test Inventory Type Name",
    "desc": "Test Inventory Type Desc",
    "is_active": 1
}

###

# CREATE NEW
post http://inventory-barang.myprojects.com/api/dashboard/inventory-types
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2MjE5NzYsIm5iZiI6MTYzMjYyMTk4NiwiZXhwIjoxNjMyNjI1NTc2LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.mMk1iy_I8FWFxriRtH4BWNLK3SzJ-Rs7zyShp8CG9mw
Content-Type: application/json

{
    "name": "Tipe inventaris test 3",
    "desc": "Deskripsi untuk tipe inventaris test 3",
    "is_active": 1
}

###

# DELETE ONE
delete http://inventory-barang.myprojects.com/api/dashboard/inventory-types/26/delete
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2Mjk5NTgsIm5iZiI6MTYzMjYyOTk2OCwiZXhwIjoxNjMyNjMzNTU4LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.dSGoj8u_914Gtsdvy-M9OHFBQ7UjFPy-a6sHS5QgtP8

###

# DELETE MULTIPLE
delete http://inventory-barang.myprojects.com/api/dashboard/inventory-types/delete/multiple
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI2Mzc5ODYsIm5iZiI6MTYzMjYzNzk5NiwiZXhwIjoxNjMyNjQxNTg2LCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.GbmmNLKSFpxnvQD14jRjAw2MqzJEkYx3m9s-ibqHBZk
Content-Type: application/json

{
    "ids": [10, 11]
}

###

