@base_url = http://iramadibatu.myprojects.com
@active_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzM3NzkwOTcsIm5iZiI6MTYzMzc3OTEwNywiZXhwIjoxNjMzNzg2Mjk3LCJkYXRhIjp7ImlkIjoiMzMiLCJmdWxsbmFtZSI6InRlc3QgdXNlciAxOCIsInVzZXJuYW1lIjoidGVzdHVzZXIxOCIsImVtYWlsIjoidGVzdHVzZXIxOEBleGFtcGxlLmNvbSIsImxldmVsIjoiYWRtaW4ifX0.FGuF2qY4ku0OO_BcDQwpnQ4luQVLUADugjcpJWmuJw0