post http://inventory-barang.myprojects.com/api/login
Content-Type: application/json

{
    "username": "testuser2",
    "password": "12345"
}

###

post http://inventory-barang.myprojects.com/api/renew/token
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0yIiwiYXVkIjoiVGhlX0F1ZDIiLCJpYXQiOjE2MzI1NTcyNzEsImRhdGEiOnsidXNlcm5hbWUiOiJ0ZXN0dXNlcjIifX0.-OpvWz0bRZitqsHXgNnW3AY6fYIJCD1uKldmxGnVVb8"
}

###

post http://inventory-barang.myprojects.com/api/logout
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0yIiwiYXVkIjoiVGhlX0F1ZDIiLCJpYXQiOjE2MzI1NTcyNzEsImRhdGEiOnsidXNlcm5hbWUiOiJ0ZXN0dXNlcjIifX0.-OpvWz0bRZitqsHXgNnW3AY6fYIJCD1uKldmxGnVVb8"
}

###
get http://inventory-barang.myprojects.com/api/dashboard
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI1OTIyOTMsIm5iZiI6MTYzMjU5MjMwMywiZXhwIjoxNjMyNTk1ODkzLCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.-Ooa_2Mza6WH7hmv4Z7Jj7bXqI2EDJqm6dunrW_OTpE

###

get http://inventory-barang.myprojects.com/api/dashboard/inventory-types
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI1OTI3NDIsIm5iZiI6MTYzMjU5Mjc1MiwiZXhwIjoxNjMyNTk2MzQyLCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.gGQTPQxNEGILXckXnPUqyqa_-8M8hTvvpuei1Hdi8U4

###

post http://inventory-barang.myprojects.com/api/dashboard/inventory-types/datatables
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaGVfQ2xhaW0xIiwiYXVkIjoiVGhlX0F1ZDEiLCJpYXQiOjE2MzI1OTI3NDIsIm5iZiI6MTYzMjU5Mjc1MiwiZXhwIjoxNjMyNTk2MzQyLCJkYXRhIjp7ImlkIjoiMiIsImZ1bGxuYW1lIjoiVGVzdCBVc2VyIDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJsZXZlbCI6InVzZXIifX0.gGQTPQxNEGILXckXnPUqyqa_-8M8hTvvpuei1Hdi8U4

###